In [1]:
# Import libaries
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest,f_regression
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
def selectkbest(indep_X, dep_Y, n):
    test = SelectKBest(score_func=f_regression, k=n)
    fit1 = test.fit(indep_X, dep_Y)
    selectk_features = fit1.transform(indep_X)
    return selectk_features

In [3]:
#Functions
def selectkbest(indep_X,dep_Y,n):
    print("enter")
    test = SelectKBest(score_func=f_regression, k=n)
    fit1= test.fit(indep_X,dep_Y)
    #summarize scores       
    selectk_features = fit1.transform(indep_X)
    return selectk_features
    
def split_scalar(indep_X,dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)    
    return X_train, X_test, y_train, y_test
    
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2
 
def Linear(X_train,y_train,X_test):       
    # Fitting K-NN to the Training set
    from sklearn.linear_model import LinearRegression
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2   
    
def svm_linear(X_train,y_train,X_test):
                
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'linear')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2  
    
def svm_NL(X_train,y_train,X_test):
                
    from sklearn.svm import SVR
    regressor = SVR(kernel = 'rbf')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2  
     

def Decision(X_train,y_train,X_test):
        
    # Fitting K-NN to the Training setC
    from sklearn.tree import DecisionTreeRegressor
    regressor = DecisionTreeRegressor(random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2  
     

def random(X_train,y_train,X_test):       
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2

In [4]:
# Create DataFrame
#def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf):
    
    dataframe=pd.DataFrame(index=['f_regression'],columns=['Linear','SVMl','SVMnl','Decision','Random'                                                                                     ])

    for number,idex in enumerate(dataframe.index):
        
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [5]:
# Read dataset CSV File
dataset1=pd.read_csv("pre_processed_synthetic_ev.csv",index_col=None)
df2 = pd.get_dummies(dataset1, drop_first=True)
df2

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52
...,...,...,...,...,...,...,...
504,1099,3.46,2.40,36.6,69.4,38.86,74.55
505,699,3.44,1.01,48.8,58.2,43.57,83.39
506,294,3.49,1.96,44.3,43.6,46.66,93.01
507,165,3.73,1.67,29.6,35.3,47.91,97.10
508,1588,3.70,4.85,40.7,96.5,33.27,64.06

In [6]:
df2.head()

,Cycles,Voltage_V,Current_A,Temperature_C,Internal_Resistance_mOhm,Capacity_Ah,SOH
0,165,3.43,3.45,29.2,40.2,47.54,95.33
1,386,4.19,3.09,30.0,48.6,46.98,90.41
2,303,4.18,3.96,28.8,39.6,46.37,91.79
3,1572,4.02,1.46,22.8,92.2,33.49,69.18
4,1708,3.30,0.89,27.7,100.9,33.65,66.52

In [7]:
df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('SOH', axis=1)
dep_Y=df2['SOH']

In [8]:
dep_Y

0      95.33
1      90.41
2      91.79
3      69.18
4      66.52
       ...
504    74.55
505    83.39
506    93.01
507    97.10
508    64.06
Name: SOH, Length: 509, dtype: float64

In [22]:
kbest = selectkbest(indep_X, dep_Y, 2)

X_train, X_test, y_train, y_test = split_scalar(kbest, dep_Y)

enter

In [26]:
kbest=selectkbest(indep_X,dep_Y,4)      

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y) 
X_train

enter

array([[ 1.05696597,  1.51872148,  1.06763438, -1.1228228 ],
       [ 1.74753308, -0.60877442,  1.81955801, -1.89547126],
       [ 1.58277849,  0.72522301,  1.5689168 , -1.59335703],
       ...,
       [ 0.79581242,  0.20772401,  0.58394082, -0.89016011],
       [-0.56954742, -0.78127408, -0.55933488,  0.7020166 ],
       [-0.09806887, -0.44777473, -0.2867076 , -0.06195042]])

In [27]:
for i in kbest:   
    r2_lin=Linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,y_train,X_test)    
    accsvml.append(r2_sl)
    
    r2_NL=svm_NL(X_train,y_train,X_test)
    accsvmnl.append(r2_NL)
    
    r2_d=Decision(X_train,y_train,X_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,y_train,X_test)
    accrf.append(r2_r)
    
    
#result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)
result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [24]:
# result k = 2
result

                Linear      SVMl     SVMnl  Decision    Random
f_regression  0.976551  0.973524  0.967875  0.958372  0.970719

In [19]:
# result k = 3
result

                Linear      SVMl     SVMnl  Decision    Random
f_regression  0.976551  0.973672  0.966673  0.946694  0.968741

In [28]:
# result k = 4
result

                Linear      SVMl    SVMnl  Decision    Random
f_regression  0.992065  0.989788  0.97349  0.978808  0.989342

In [13]:
# result k = 5
result

                Linear      SVMl    SVMnl  Decision    Random
f_regression  0.992065  0.989788  0.97349  0.978808  0.989342